# Generated by Django 5.0.3 on 2024-05-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportID', models.AutoField(primary_key=True, serialize=False)),
                ('reporterID', models.IntegerField()),
                ('reporterName', models.CharField(max_length=255)),
                ('imageFilePath', models.CharField(blank=True, max_length=255, null=True)),
                ('imageName', models.CharField(blank=True, max_length=100, null=True)),
                ('operationLineNumber', models.CharField(max_length=255)),
                ('problemDescription', models.TextField()),
            ],
            options={
                'db_table': 'report',
            },
        ),
    ]
