# Generated by Django 5.0.3 on 2024-05-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_report_reporterid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='imageFilePath',
        ),
        migrations.RemoveField(
            model_name='report',
            name='imageName',
        ),
        migrations.AddField(
            model_name='report',
            name='imageData',
            field=models.ImageField(blank=True, null=True, upload_to='reportImages/% Y/% m/% d/'),
        ),
    ]
