# Generated by Django 5.0.3 on 2024-05-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_report_imagefilepath_remove_report_imagename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='imageData',
            field=models.ImageField(blank=True, null=True, upload_to='reportImages/'),
        ),
    ]
