# Generated by Django 5.0.3 on 2024-05-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_report_imagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='confirmedBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='datetime',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sentBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sentTo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
