# Generated by Django 5.0.3 on 2024-05-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_report_confirmedby_report_datetime_report_sentby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='problemCategory',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
