# Generated by Django 5.0.6 on 2024-05-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_report_imagedata_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(default='0', max_length=255, null=True),
        ),
    ]
