# Generated by Django 5.0.6 on 2024-05-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, choices=[('safety', 'Safety'), ('maintenance', 'Maintenance'), ('engineering', 'Engineering'), ('qa', 'Quality Assurance')], max_length=20, null=True),
        ),
    ]
