# Generated by Django 5.0.3 on 2024-05-29 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profile_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageData', models.ImageField(blank=True, null=True, upload_to='reportImages/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.report')),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
