# Generated by Django 5.0.3 on 2024-05-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='duteDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='emailNotifyDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
