# Generated by Django 5.0.3 on 2024-05-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_report_dutedate_report_emailnotifydate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='duteDate',
            new_name='dueDate',
        ),
    ]
