# Generated by Django 5.0.3 on 2024-05-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_dutedate_report_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, choices=[('1', 'Safety'), ('2', 'Maintenance'), ('3', 'Engineering'), ('4', 'Quality Assurance')], max_length=20, null=True),
        ),
    ]
