# Generated by Django 5.0.6 on 2024-05-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_operationline_id_alter_profession_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='operation_line_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profession',
        ),
        migrations.AddField(
            model_name='profile',
            name='operation_line_no',
            field=models.ManyToManyField(blank=True, null=True, to='main.operationline'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.ManyToManyField(blank=True, null=True, to='main.profession'),
        ),
    ]
