# Generated by Django 5.0.6 on 2024-05-31 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_profile_operation_line_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='operation_line_no',
            field=models.ManyToManyField(blank=True, to='main.operationline'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.ManyToManyField(blank=True, to='main.profession'),
        ),
    ]
