# Generated by Django 5.0.6 on 2024-06-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_profile_operation_line_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Approved'), ('2', 'Sent')], default='0', max_length=1),
        ),
    ]
