# Generated by Django 5.0.6 on 2024-06-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='operationLineNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
