# Generated by Django 5.0.6 on 2024-06-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_report_operationlinenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='operationLineNumber',
            field=models.CharField(max_length=255),
        ),
    ]
