# Generated by Django 5.0.6 on 2024-06-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_report_operationlinenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='machineNumber',
            field=models.TextField(blank=True, null=True),
        ),
    ]
