# Generated by Django 5.0.6 on 2024-06-05 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_report_machinenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.report'),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('solutionID', models.AutoField(primary_key=True, serialize=False)),
                ('solverName', models.CharField(max_length=255, null=True)),
                ('solutionState', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('description', models.TextField(null=True)),
                ('datetime', models.CharField(max_length=255, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.report')),
            ],
            options={
                'db_table': 'solution',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.solution'),
        ),
    ]
