# Generated by Django 5.0.6 on 2024-06-06 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_image_solution_imagesolution'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imagesolution',
            table='image_solution',
        ),
    ]
