# Generated by Django 5.0.6 on 2024-06-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_imagesolution_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='solvedBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
