# Generated by Django 5.0.6 on 2024-06-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_report_solvedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Approved'), ('2', 'Sent'), ('3', 'Solved')], default='0', max_length=1),
        ),
    ]
