# Generated by Django 5.0.3 on 2024-06-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_report_machinenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Approved'), ('2', 'Sent'), ('3', 'Solved'), ('4', 'Rejected')], default='0', max_length=1),
        ),
    ]
