# Generated by Django 5.0.3 on 2024-06-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_report_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='solutionState',
        ),
    ]
