# Generated by Django 5.0.6 on 2024-06-13 08:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_solution_solutionstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subCategory', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='subCategory',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
