# Generated by Django 5.0.3 on 2024-06-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_profession_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Approved'), ('2', 'Validated'), ('3', 'Sent'), ('4', 'Solved'), ('5', 'Finished'), ('6', 'Rejected')], default='0', max_length=1),
        ),
    ]
